plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.3'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.rra.project'
version = '0.0.1-SNAPSHOT'
description = 'riot-api'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

configurations {
    mockitoAgent
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.springframework.boot:spring-boot-starter-cache'
    implementation 'com.bucket4j:bucket4j_jdk17-core:8.14.0'
    implementation 'com.github.ben-manes.caffeine:caffeine'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    mockitoAgent('org.mockito:mockito-core') {
        transitive = false
    }
}

tasks.named('test') {
    useJUnitPlatform()
    jvmArgs += "-javaagent:${configurations.mockitoAgent.asPath}"
}


tasks.named('bootRun') {
    doFirst {
        def envFile = file('.env')
        if (envFile.exists()) {
            envFile.eachLine { line ->
                line = line.trim()
                if (line && !line.startsWith('#') && line.contains('=')) {
                    def (key, value) = line.split('=', 2)
                    environment(key.trim(), value.trim())
                }
            }
        }
    }
}